### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by AnonJohn** [Mael-J/mstarpy#5]
When trying to run the example code to retrieve a NAV for a fund, morningstar's site is not responsive:

history = fund.nav(start_date=start_date,end_date=end_date, frequency="daily")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "../lib/python3.10/site-packages/mstarpy/funds.py", line 869, in nav
    return self.TimeSeries(["nav","totalReturn"],
  File "...local/lib/python3.10/site-packages/mstarpy/security.py", line 242, in TimeSeries
    not_200_response(url,response)
  File "../local/lib/python3.10/site-packages/mstarpy/error.py", line 10, in not_200_response
    raise ConnectionError(f"Error {response.status_code} for the api {url}. Message : {response.reason}.")
ConnectionError: Error 417 for the api https://www.us-api.morningstar.com/QS-markets/chartservice/v2/timeseries?query=F00000JTEF:nav,totalReturn&frequency=d&startDate=2023-01-01&endDate=2023-03-02&trackMarketData=3.6.3&instid=MSERP. Message : Unknown.

**Comment by AnonJohn** [comment]
Was using an old library version. Apologies. Works with latest.
